### ISSUE TITLE
Constraint for arrays that need to contain at least one element

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#182]
If a BAG-OF-construct requires at least one element (i.e. BAG {1..*} OF...) the projectgenerator should configure the form so that at least one element has to be selected before the green tick appears.
Currently the green tick appears even if no values are selected. Hence data can be saved that is not ili-model-compliant.

![bag_of_1_n](https://user-images.githubusercontent.com/23503534/39192943-eb6f80ec-47c9-11e8-8043-015377e99c3f.png)

The prerequisite seem to be missing in the PostGIS metatables:
https://github.com/claeis/ili2db/issues/171

**Comment by pramisters** [comment]
Model example: 
[ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt](https://github.com/opengisch/projectgenerator/files/1943141/ZG_Naturschutz_und_Erholungsinfrastruktur_V1.txt)

**Comment by m-kuhn** [comment]
The value relation widget with multi selection currently maintains the value in the format `{1, 2, 3}` which is non-standard and not even supported by QGIS' own expression engine.

We could workaround this issue by parsing the string within the constraint expression.

I'd prefer to fix the underlying issue first and make this widget capable of handling arrays. Since the ili2db issue is still open, how high priority is this?

**Comment by pramisters** [comment]
Not that high, but I also didn't get an answer so far to claeis/ili2db#171
Which constraint expression are you referring to?

**Comment by m-kuhn** [comment]
layer properties -> fields and forms -> constraints

**Comment by pramisters** [comment]
You mean something like:  `array_length("typ") > 0` ?
Although the background turns yellow, the OK-Button is still active.
When "Enforce expression constrained" the OK-Button is inactive, but doe

**Comment by m-kuhn** [comment]
Exactly this :+1:

**Comment by m-kuhn** [comment]
Fixed by #363
