### ISSUE TITLE
Configure precision and remove duplicate nodes

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#237]
Based on ili properties

**Comment by m-kuhn** [comment]
https://github.com/claeis/ili2db/issues/226

**Comment by p1d1d1** [comment]
Should be fixed via this: https://github.com/claeis/ili2db/releases/tag/ili2db-4.0.0

**Comment by m-kuhn** [comment]
Thanks, ili2db label removed.

**Comment by signedav** [comment]
@m-kuhn Can you precise the request: 
I assume that it's about to get the precision of the coordinates from the precision the extent coordinates are stored?
But where the precision has to be set? For the geometry columns? And what is meant with the duplicate nodes?

**Comment by signedav** [comment]
Note to myself. The layers extend i emitted by getting:
```
                    SELECT string_agg(setting, ';' ORDER BY CASE
                        WHEN cprop."tag"='ch.ehi.ili2db.c1Min' THEN 1
                        WHEN cprop."tag"='ch.ehi.ili2db.c2Min' THEN 2
                        WHEN cprop."tag"='ch.ehi.ili2db.c1Max' THEN 3
                        WHEN cprop."tag"='ch.ehi.ili2db.c2Max' THEN 4
                        END)
```

**Comment by signedav** [comment]
There is still confusion left. Since we should get the information from the extent values stored in the database, I thought it's about decimal places of the coordinates. But apparently it's about setting the `geometryPosition` used for e.g. the _snap to grid_ functionality. Means: "Geometries which are edited on this layer will be rounded to multiples of this value".

So I guess we should not take the precision from the extends decimal places, or should we?

Like this:
Extend: `2460000.000;1045000.000;2870000.000;1310000.000` ( `COORD` from `GeometryCHLV95_V1` )
GeometryPrecision: 0.001 or 1000.000 ?

**Comment by m-kuhn** [comment]
x.000 (3 places) INTERLIS --> 0.001 (millimeter) precision

**Comment by signedav** [comment]
And there are no > 1 m precision set, right?

**Comment by m-kuhn** [comment]
Not that I know of
