### ISSUE TITLE
The project does not save the properties in attributes form

### ISSUE THREAD

**Issue by jhonalex06** [opengisch/QgisModelBaker#302]
[Short description of problem here]

The issue occurs when I create a new project from an .ili model and save it directly (without touching anything else) as QGIS Project. The project does not save the properties in attributes form, as you can see in the figure below.

### Reproduction Steps:

1. Open QGIS.
2. Create a new project in Geopackage with QgisModelBaker.
3. Save the project.
4. Save the project with other name.
5. Open the properties of the punto Vector Layer.
6. Select all fields in Attributes Form.
7. Click on Apply.
8. Click on ok.
9. Open both projects with Meld or other app to see the diff.
10. Compare and check the changes.

### Expected behavior:

The properties are stored when the project is created with QgisModelBaker and saved in QGIS.

### Observed behavior:

The properties are not stored when the project is created with QgisModelBaker and saved in QGIS.

### Screenshots and GIFs

![Screenshot from 2019-05-09 15-36-22](https://user-images.githubusercontent.com/27906888/57535424-cf378b80-7307-11e9-8505-e25f030a39c1.png)
![Screenshot from 2019-05-09 15-35-20](https://user-images.githubusercontent.com/27906888/57535425-d1014f00-7307-11e9-906a-ee767ba028ef.png)
![issueMatias2](https://user-images.githubusercontent.com/27906888/57535435-d52d6c80-7307-11e9-8b1e-5de1d17152ac.gif)

**QgisModelBaker version:** 4.2.2

**Comment by m-kuhn** [comment]
The properties are normally automatically created upon first usage (attribute form opened, layer properties opened, field values represented somewhere, ...).
Whenever one goes to the layer properties and accepts the layer properties, they are written to the layer (materialized). This is actually QGIS behaviour and shouldn't hurt a lot because saving default values or obtaining default values again shouldn't change anything in behaviour.

What is the underlying issue for this request (some I can think of: managing the project in git, usage in QField, ...)

**Comment by gacarrillor** [comment]
The issue is to be unable to use the just-configured layers for a QField project. We wouldn't like to tell our users: Please open the layer properties for the configuration to take effect. 

> The properties are normally automatically created upon first usage (attribute form opened, layer properties opened, field values represented somewhere, ...).

Do you know of any automatic way to apply the configuration without dealing with the GUI? Something like: 
`my_layer.applyConfiguration()`?

**Comment by m-kuhn** [comment]
It could also be solved on QField side

**Comment by gacarrillor** [comment]
Solved for QField in https://github.com/opengisch/QField/pull/689
