### ISSUE TITLE
Make ili2db deployment independent from system java

### ISSUE THREAD

**Issue by uncoyote** [opengisch/QgisModelBaker#313]
For the typical qgis user, the required java settings for ili2db are non-trivial. Why not pack the required jre into modelbaker?

**Comment by m-kuhn** [comment]
Currently, java is detected automatically, no more manual setup should be required ([since release 4.1.1](https://github.com/opengisch/QgisModelBaker/releases/tag/v4.1.1). At the moment, the user only has to download and install manually (link to installer is provided as soon as the lack of JRE is detected). If there are problems with the current logic, the highest priority should be to iron these out IMO.

The main obstacle right now is that the newest version of Java doesn't work, but that should also soon no longer be an issue because of ili2db 4.

Packaging the installer

* needs proper checking of licenses (we are only allowed to distribute GPL compatible binaries through the QGIS plugin repository)
* will increase the size of the plugin
* will open the question if this should also be done for other platforms (mac) too
* will not resolve issues in enterprise environments with managed computers where only administrators can install software

With this in mind, I tend towards not completely packaging the installer, but making the steps to obtain and install JRE as easy as possible.

**Comment by pramisters** [comment]
JRE must NOT be installed by Model Baker as JRE is often distributed and installed by a managed environment.

**Comment by m-kuhn** [comment]
Should we close this issue?
