### ISSUE TITLE
unknown referenced object from catalogue

### ISSUE THREAD

**Issue by KTAI-GIS** [opengisch/QgisModelBaker#322]
[AI_test_201907121551.zip](https://github.com/opengisch/QgisModelBaker/files/3386649/AI_test_201907121551.zip)
Error: unknown referenced object Nutzungsplanung_Hauptnutzung_V1_1.Hauptnutzung_CH.Hauptnutzung_CH TID ch.admin.are.nutzungsplanung.hauptnutzung_ch.11 referenced from Zonenplan_AI.Geobasisdaten.Typ_Kt TID 23738544-20bd-465f-be6d-48487b508607
1. Create DB
2. Import Hauptnutzung CH Catalogue
3. Import AI Catalogue

The same workflow with ili2db works well.

**Comment by m-kuhn** [comment]
Which version of Model Baker are you using? Which version of ili2db did you use for the control workflow which works well? Can you add the ili2db commands which work well?

Thank you in advance.

**Comment by KTAI-GIS** [comment]
I used [https://github.com/opengisch/QgisModelBaker/releases/tag/5.0.0-beta](url) (4.0.0-BETA ???)
and attached is my Import Batch file. The Import is similar to the canton GL Import.

Best regards

[import.zip](https://github.com/opengisch/QgisModelBaker/files/3400594/import.zip)

**Comment by m-kuhn** [comment]
Thank you for the feedback.

The issue is that we do a `--doSchemaImport` when importing data, to be able to directly generate a database and import data in one single action.
It seems, that in this case here, it will overwrite the geopackage when the second import (AI Catalogue) happens and delete the first imported dialog (Hauptnutzung CH Catalogue).

I would suggest we drop the `--doSchemaImport` since it currently apparently overwrites any data unconditionally.

We can still reintroduce it later (or directly call --schemaimport in a pre-processing step) to allow drag-and-drop of xtf files into QGIS or do similar tricks.

**Comment by KTAI-GIS** [comment]
It's probably a good idea to separate the Schema creation and catalogue/data import. Claude Eisenhut also recommend this.

**Comment by m-kuhn** [comment]
Good, I'll add a patch for this :+1: 

Long term and concept wise I think we still have a bit more flexibility in a gui application than in a non-interactive command line application.

**Comment by KTAI-GIS** [comment]
I completly agree with you but to handle things like --nameByTopic or --dataset which are Project dependent the GUI gets confusing fast. What do you think of the ability to override the default command-line definition with a configuration file imported from the GUI. This enables project dependent configurations.

**Comment by m-kuhn** [comment]
`--doSchemaImport` is removed for now.

For the configuration, that is very much related to the interlis+ project, where project requirement can be specified via a .ini file.
