### ISSUE TITLE
Export with specific model doesn't work

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#342]
If only a specific model is chosen at export, still all of the models are exported. In the ili2db export-option --models should only be listed the chosen models. Then it works.

![image](https://user-images.githubusercontent.com/26796989/64535418-8c1e1100-d317-11e9-9ec8-ead880ae0455.png)

**Comment by signedav** [comment]
I'm confused. As we discussed back then on the PR #249, we decided not to use `--models` but `--exportModels` instead, since it's suggested in the docs. But the docs are still unclear: https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst

> `--export`
> Exportiert Daten aus der Datenbank in eine Transferdatei.
> Mit dem Parameter --models, --topics, --baskets oder --dataset wird definiert, welche Daten exportiert werden.

... tells us we should use `--models`

> `--exportModels`
> Beim Export/Prüfen werden die Daten gem. dem gegebenen Export-Modell exportiert/geprüft. Ohne die Option --exportModels werden die Daten so wie sie erfasst sind (bzw. importiert wurden), exportiert/validiert.

.. tells us we should use `--exportModels`

I wonder why we decided `--exportModels` when it doesn't work. I don't think that we didn't test it.

Does anyone know more about this @m-kuhn @romefi ?
It's possible that this works with ili2db version 4, but I haven't checked... 

Otherwise it's an easy fix to use `--models` instead. But it would be nice, if we know why we are doing something :-)

**Comment by pramisters** [comment]
I try to dissolve the confusion:

The conclusion in #249 that the docs  (generally) suggest to use `--exportModels` for export is NOT correct.

- `--export` together with `--models` [modelname] is correct and appropriate for most of the cases
- The option`--models` is used both for import (to generate the table structures of a specific model of the model file (ILI)) and for export
- `--exportModels` instead of `--models` can only be used specifically for base models (that have been extended) or for translated models. 
> `--exportModels` : Als Export-Modelle sind Basis-Modelle (also z.B. Bundes-Modell statt Kantons-Modell) oder übersetzte Modelle (also z.B. DM_IT statt DM_DE) zulässig).

In the example above `--exportModels` doesn't work because the model that is specified as [modelname] isn't a base model.

**Comment by romefi** [comment]
Thanks @pramisters. So the export should be done with `--models`. Means only the checked models at export should be listet in `--models`.

**Comment by signedav** [comment]
Thanks @pramisters and yes @romefi I guess in this case export with `--models` should be done.

But shouldn't we support `--exportModels` as well? As far as I understood it, it could be the case that someone needs your data in the structure of `Nutzungsplanung_LV95_V1_1`. Since your model `Nutzungsplanung_SH_LV95_V4_0` bases on it (correct me if I'm wrong), it could be the case the export should be done like:
```
ili2pg-4.4.3.jar --dbhost localhost --dbusr postgres --dbpwd *** --dbdatabase bakery --dbschema nutzungsplanungsh --export --exportModels Nutzungsplanung_LV95_V1_1 --models Nutzungsplanung_SH_LV95_V4_0 nutzungsplanung_02.xtf
```
If so, we need to find out how we recognize a base model in a cantonal model...

**Comment by pramisters** [comment]
@romefi 
Yes.

@signedav 
Not sure if you can use `--models` and `--exportModels` together in one command. Needs a short test or: Ask @claeis
Anyway, to me it doesn't make sense to have redundant data (of both base and extended model) in one single xtf file as the data of the base model is already included in the data of the extended model. I woukd say: either ... or.

Yes, if we implement `--exportModels` we have to recognize whether a chosen model is a base model or not.
But, keep in mind, depending on the extension, an export of an underlaying base model can be logically impossible, e.g. if an extended enumeration (e.g. an additional element) can't be mapped back to the original enumeration.

If I remember correctly, I have successfully tested (in the past) an export of an underlaying base model (MGDM) of an extended cantonal model just with `--models`. So I wonder why @claeis changed that to two different export options in version 3.10.9

**Comment by signedav** [comment]
Thanks for the info @pramisters

**Comment by claeis** [comment]
- ```--models``` is one way to set the scope/extent of the exported data (```--baskets``` is the most specific way to do this).
- ```--exportModels``` is a different thing. It defines how the selected scope/extent is exported

**Comment by signedav** [comment]
Maybe this should be supported in future. See #665
