### ISSUE TITLE
Warning if schema exists

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#365]
Model Baker should show a warning if a schema already exists.
Most likely it's an error since users don't normally generate multiple models in a single schema.

**Comment by signedav** [comment]
**First approach:**

I think this is the normal use case:
1. User enters schema
2. User presses Create
3. Message that the schema exists
4. User has to change the schema
5. User presses Create
6. Import is made

Should the user still be able to import on an existing schema?
Means on 4. The user can a. select the key "Import without validation", b. checkbox to import on existing schema, c. do nothing, and still on the second time it does not check anymore for the schema existence.

Here I would go for a.

But I would prefer a **second approach**
1. User enters schema
2. On text change it checks, if the schema exists and if yes, the text field turns orange
3. User presses Create
4. Import is made, no matter if schema has been existing already or not.

But on this approach the confusion comes up with the Geopackage implementation, because there the text field gets orange, when the file does not exist. There the behavior would be the complete opposite. So I wonder, if we should improve the solution like this:
- GeoPackage will be created, if not existing
- Text field turns orange when the Geopackage is existing (instead of not existing)

Because what I belief is, that if someone makes an import to a GeoPackage, then he/she wants to have it mostly on a new one.

**On generating from DB**
On generating from DB we could make the opposite: Turn orange if the Geopackage or the Schema does not exist. Or  we keep it there, how it is already: Info Message in the Log Pannel when pressing Create

What is your opinion @m-kuhn @romefi ?

**Comment by romefi** [comment]
> Should the user still be able to import on an existing schema?

Yes, this should still be possible. I.e. to update data.

I'm not sure if the orange marker is the right approach. For me, when a field is orange, then something is wrong. When a schema or geopackage already exists, it's not per se wrong. The purpose of this issue is to inform the user, if a schema or geopackage already exists. So my approach would be (which in my eyes also match to the common behavior of QGIS):

1. Mask stays as it is
2. When creating schema or geopackage Model Baker tests, if schema or geopackage exists
3. If they exist, prompt a messagebox like "The Schema/Geopackage already exists. Do you want to continue?" Yes -> go on, No -> cancel

What do you think?

**Comment by signedav** [comment]
Okay, like this:

![image](https://user-images.githubusercontent.com/28384354/91711947-1b56b100-eb87-11ea-97d9-16947c4f4f5b.png)
