### ISSUE TITLE
Skip loading of geometry classes (GeometryCHLV95_V1) as layers

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#409]
Geometry classes derived from GeometryCHLV95_V1 like

- linestructure
- multiline
- multisurface
- surfacestructure

shouldn't be loaded into the project as layers

Tested with loading from Postgresql (data structure manually created with ili2pg)

![image](https://user-images.githubusercontent.com/884476/84050823-89d40a80-a9ae-11ea-84fd-a6280e240183.png)

Testmodel: http://geo.so.ch/models/ALW/SO_ALW_Strukturverbesserungen_20190912.ili

**Comment by m-kuhn** [comment]
I agree.

I think they only need to be hidden when the appropriate `@ili2db.mapping=Multi[Type]` attribute is set?
Otherwise it's even harder to use "unoptimized" models. While they are uncomfortable to use anyway, it's still often the case that they exist and hiding these tables away will produce strange results (e.g. dataimport not showing up).

**Comment by pramisters** [comment]
@m-kuhn:
No, there are some exceptions. The most important exception is the one Andreas mentioned in his example:
If the multi-geometry definitions from the federal base models (GeometryCHLV95_V1) are used unchanged, ili2pg maps it to native multi-geometry database types in PostGIS even if there's no meta-attribute `@ili2db.mapping=Multi[Type]` present.
I.e. if ili2pg generates native multi-geometry database types, the classes:

- linestructure
- multiline
- surfacestructure
- multisurface
- pointstructure
- multipoint

are not used, don't need to be filled with data and therefore don't need to be imported as project layers.

**Comment by m-kuhn** [comment]
@pramisters thanks for clarifying that there are circumstances where multi types are generated without `ili2db.mapping attribute`.
Are there also situations where these tables are generated and are in use and therefore should not be hidden?

**Comment by pramisters** [comment]
@m-kuhn
Yes, if it's not the general case, i.e. if it's NOT one of the exceptions (see list in section "_Strukturattribute_" after "_Bei den folgenden Strukturen wird bei Smart-Mapping für die Strukturattribute eine alternative Abbildung verwendet..._" in Claude's doc: https://github.com/claeis/ili2db/blob/master/docs/ili2db.rst).
For "Smart-Mapping" see explanations for the options `--coalesce[xxx]` in the doc.
(I forget to mention that the `--coalesce[xxx]` is necessary so that multi types are generated in case of structure elements)

So, if you don't load the mentioned tables for distributed STRUCTUREs in those exceptions it covers all the desired cases when you don't want/need the tables in the project.

The problem will be obsolete with INTERLIS 2.4 when multi types are supported natively and no detour with STRUCTUREs is needed anymore.

**Comment by m-kuhn** [comment]
`t_ili2db_classname` can be used to detect LineStructure, MultiLine etc based tables.

![image](https://user-images.githubusercontent.com/588407/84133909-15e64080-aa48-11ea-98c0-0e353b959afe.png)

`t_ili2db_meta_attrs` can be used to detect `ili2db.mapping`

![image](https://user-images.githubusercontent.com/588407/84134430-da984180-aa48-11ea-9e0c-5b68a2883feb.png)

**Comment by andreasneumann** [comment]
> `t_ili2db_classname` can be used to detect LineStructure, MultiLine etc based tables.

Sounds like a good solution

**Comment by andreasneumann** [comment]
> The problem will be obsolete with INTERLIS 2.4 when multi types are supported natively and no detour with STRUCTUREs is needed anymore.

Thank god - I mean the "INTERLIS-gods" ;-)
