### ISSUE TITLE
Add global ili2pg configuration option "--dbparams" to enable SSL connections

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#458]
When a SSL connection is required in ili2db we need to be able to specify the following additional parameter:

```
--dbparams dbparams.txt
```
with the file content
```
sslmode=require
```
This needs to be attached to all ili2pg connections used throughout QGIS Model Baker.

The suggestion is to add it in the global "Settings" Dialogue, either in "General" or allow to edit the "Ili2DBOptions".

**Comment by m-kuhn** [comment]
Good input.
I think this should go to the rest of the connection parameters since it's database specific. If this is too visible, maybe we can hide away those in a collapsible group box or otherwise to leave the fields that are usually changed (schema/database) more prominently?

ili2db options are editable already when you create a new schema.

**Comment by andreasneumann** [comment]
Yes - good idea to include it there. Thanks!

**Comment by m-kuhn** [comment]
It could also be added to pg_service.conf

**Comment by signedav** [comment]
@domi4484 Is this implemented?

**Comment by domi4484** [comment]
Some last bits of the sslmode implementation where missing. The parameter was used for direct database connections from modelbaker, but it was not passed to ili2db.
This [pull request](https://github.com/opengisch/QgisModelBakerLibrary/pull/4) add that bits.
