### ISSUE TITLE
Tables are imported twice when creating a project from a model with extended classes

### ISSUE THREAD

**Issue by pramisters** [opengisch/QgisModelBaker#461]
Underlaying tables don't need to be populated and thus don't need to be imported into the project layers.

Example: https://models.geo.zg.ch/ARV/ZG_Nutzungsplanung_V1_1.ili

**Comment by signedav** [comment]
Tables are not imported twice, but yes both tables are imported. The ones from the base model and the one from the extended model. This can be very confusing and - since usually the extended tables are named the same - ModelBaker creates the layers with the same names.

See issue here #662

I think there are several approaches:
(talking here as "base tables" from tables that are modeled as classes in a base model (like national) and extended in a extended model (like cantonal).
- ili2db should not create the base tables (don't know if it's possible)
- model baker should not load the base tables
- model baker should hide the base tables in the layertree
- model baker should name the base tables with different names (while this appears to be something that should be done anyway, I hesitate to "just do it" because if one of the other approaches are implemented, this would lead to legacy stuff
- any other ideas?

What is your opinion here @romefi ?
Or @zigertiger at GL you used to have those kind of models as well as far as I know. How should model baker handle that?

**Comment by zigertiger** [comment]
IMHO ili2pg should actually create the base tables since it must be possible to export data according to the base model (the complete model information of the base model has to be present in the database...)
Model baker should not load the base tables whatsoever because the user decided to implement the "specialised model" XYZ.

**Comment by signedav** [comment]
Cool. Thanks for your inputs. Then I guess the requiremrnt is that Modelbaker should detect classes that have been extended and only load the extended class.

**Comment by signedav** [comment]
In principle, it's about the idea that a base class that was extended with EXTENDED (not EXTENDS) should not be displayed in the QGIS project, and no QGIS relations to it should be created (i.e. should not be loaded by the Model Baker).

Is that given that such classes are "never" needed? Not even if it is a model internal extension?

E.g.
```
MODEL Another_City_V1_1 (en) AT "mailto:localhost" VERSION "2021-07-20" =

  TOPIC Constructions =
    CLASS Building  =
      Name : MANDATORY TEXT*99;
    END Building;

    CLASS Street =
        Type : MANDATORY TEXT*99;
    END Street;

    ASSOCIATION Building_Street =
      Street -- {0..1} Street;
      Building -- {0..*} Building;
    END Building_Street;
  END Constructions;


  TOPIC Business EXTENDS Another_City_V1_1.Constructions =
    OID AS INTERLIS.UUIDOID;

    CLASS Building (EXTENDED) =
      Company : TEXT*99;
    END Building;

  END Business;

END Another_City_V1_1.


```

If so, then Model Baker needs the information, if a CLASS become EXTENDED by another CLASS. This could b e checked in the table `t_ili2db_inhertiance` if it has the same classname. Not sure if there is a more elegant way.

**Comment by zigertiger** [comment]
Unfortunately, you would nonetheless want to enter data for "Street" in the topic "Constructions" regardless of any furhter extension that might exist...
The only case where this would be excluded beforehand is when the topic "Construction" was abstract as a whole.

So, "id depends"... ¯\_(ツ)_/¯

**Comment by signedav** [comment]
@zigertiger But then we would only hide the tables of an abstract TOPIC. So in @pramisters example, the buildings of both TOPICS should be loaded (because `Geobasisdaten` of `Nutzungsplanung_LV95_V1_1` is not ABSTRACT).

**Comment by zigertiger** [comment]
Yes.

**Comment by signedav** [comment]
Okay, thanks.

Then I think to resolve this issue here it would make sense to have an improved layer naming. Recognize it the same way, like mentioned here https://github.com/opengisch/QgisModelBaker/issues/461#issuecomment-1113044948 and use the "normal" name like "Buildings" for the extended layers (and there maybe it's still a duplicate - but I think this use case is rare).

And concerning the abstract TOPIC I would need to check out if there is any information in the meta-tables of ili2db to find out if the TOPIC is abstract.

**Comment by signedav** [comment]
So a solution could be 1. the improved naming by naming the table (instead the lowest instance) with the model and topic name. A 2. step would be that the tables from an abstract topic are not loaded, but I currently don't know where to get this info (would need to check with Claude). But be aware @pramisters that this won't fix your use case. But at least you have more descriptive layer names.

A completely different approach is to "ask" the user what tables should be loaded in the GUI. But this makes it more complex of course :thinking:
