### ISSUE TITLE
ILI and ITF for "Melioration_Kt_SHLV95"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [opengisch/QgisModelBaker#469]
My knowledge in QGis is limited, so maybe it is a User-issue..

I have ILI and ITF for "Melioration_Kt_SHLV95", and the ILI contains a 
"    TABLE Masse = .."
The ITF contains a section with 12 objects, beginning with
TABL Masse
OBJE 1 ...

Importing it to QGis, I get a layer displayed as "--- Masse) [12]" - "line" is correct, the bracket) is strange, 12 objects are correct
Looking at the table "Masse)" I have 12 rows, but only with "T_Id" and nothing else ..

Is it a known problem?

**Comment by m-kuhn** [comment]
This sounds like something specific to this model.
In general the focus of this project is for Interlis 2 models, but fixes for Interlis 1 models can be considered too.

**Comment by romefi** [comment]
As the model is made by my office, I gladly share my thoughts :)

I tested with an ITF we got from a commune and the "Masse" looks good (except for the MassPos).

![image](https://user-images.githubusercontent.com/26796989/107372815-1dce1700-6ae6-11eb-959a-eeeac837d4be.png)

Are you sure that ILI and ITF are from the same timestamp? I know that there have been many changes in the ILI, but the modelname was always Melioration_Kt_SHLV95. So if your ITF is older than the newest ILI on models.geo.sh.ch, it may cause a problem. It's just a suggestion. Otherwise we would need the data to make proper tests...

**Comment by Pierre-de-la-Verre** [comment]
The problem starts already when creating the "Geopackage"; no data needed for this:
![grafik](https://user-images.githubusercontent.com/13277944/107390042-94274500-6af7-11eb-999a-59d307f21d8c.png)
QGis 3.16.3-Hannover
Modelbaker 6.3.4

I compared the local and the downloaded ILI - it's the same (see also #470 )

**Comment by romefi** [comment]
Right, I was testing with Postgis, where the problem doesn't occur. Got same issue in Geopackage.

DB looks good:
![image](https://user-images.githubusercontent.com/26796989/107393442-1a915600-6afb-11eb-8a89-1e3f15ae604c.png)

qgs is wrong:
![image](https://user-images.githubusercontent.com/26796989/107393542-3563ca80-6afb-11eb-9cb8-81ae9f66a44f.png)

@m-kuhn could you take a look why it fails with Geopackage?

**Comment by Pierre-de-la-Verre** [comment]
Thanks for confirmation.
It is not only in that special ILI, it happens also in SIA and TG12 .. - and maybe more.

**Comment by Pierre-de-la-Verre** [comment]
> 
> @m-kuhn could you take a look why it fails with Geopackage?

What (and when) will be the next steps? I'm not sure if I can continue my work when it is not clear if there are (relevant?) issues ...

**Comment by m-kuhn** [comment]
Is there a dataset available to reproduce this issue?

I'm out out of office this week, I can have a look next week

**Comment by Pierre-de-la-Verre** [comment]
Just take one of the common ILIs, like DM01AVTG24LV95.ili or sh_melioration_ili_v9_11_lv95.ili, and create a new "Interlis (Geopackage)". You will see the brackets, in "DM.." much more than in "SH.."

**Comment by Pierre-de-la-Verre** [comment]
My project which I wanted to do with ModelBaker will be short of time soon so I want to ask if this question will be covered this week?

**Comment by m-kuhn** [comment]
Good timing, today I actually have some time.

First assessment:

This is the INTERLIS Class Masse.
It has a point geometry and a an (optional) line geometry

```
    TABLE Masse =                    !! nur fuer effektive Einmasse gedacht,
                                     !! keine Leitungsabschnittslaengen erfassen
      Mass:        REAL42;
      Gemarkung:   Gemeinden;            !! Defaultwert durch Benutzer zu setzen
      Erhebungsart: (Feldaufnahme, Planabgriff)   // Default = Feldaufnahme //;
      MassPos:     LKoordmm;                  !! Anschrift Attributinhalt "Mass"
      MassOri:     Orientierung                          // Default = 100.0 //;
      MassHAli:    OPTIONAL HALIGNMENT              // undefiniert = Center //;
      MassVAli:    OPTIONAL VALIGNMENT              // undefiniert = Bottom //;
      MassGroesse: OPTIONAL Schriftgroesse          // undefiniert = mittel //;
      Geometrie:   OPTIONAL POLYLINE WITH                       !! Geometrie der
                   (STRAIGHTS, ARCS) VERTEX LKoordmm;           !! Masslinie
    NO IDENT
    END Masse;

```

There are two tables in the geopackage:

 - masse (Point geometry, with attributes)
 - masse_geometry (Line geometry, no attributes except for T_Id)

The point layer is loaded correctly
The line layer has the wrong name (`Masse)` instead of something like `Masse.Geometrie`). This is only a visual problem, we will have a look at that. Meanwhile, just change the name manually in QGIS for your current project.

The advanced question is how to properly map the line layer to a point layer.
There are various ways to do that and its connected to the particular workflow. I am not sure if there is one right way which model baker should be doing by itself.
You could use a relation reference widget to connect the two and manually connect the masslinie to a text position where needed. Or create a virtual layer to manage the line as "main objects" and the text positions with the labeling tools. These are data model and workflow specific questions hard to answer in a generic way.

**Comment by Pierre-de-la-Verre** [comment]
Thanks. Could you also take a look at the problem, mentioned in the first post - it does not read all data to the table ..

**Comment by m-kuhn** [comment]
The rest of the attributes is in the corresponding point layer, linked via T_Id.

**Comment by Pierre-de-la-Verre** [comment]
Thanks for your replies, it is OK for me now. 
I let it up to you to close this issue, depending on the bracket-issue in the layers-
