### ISSUE TITLE
T_Id as value in referencing children when `--createEnumTabsWithId`

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#500]
The generated ili2db command contains `--createEnumTabs` and when ili2db > 3 `--createEnumTabsWithId` as well what overrides the first setting.

With `--enumWithTabs`:
![image005](https://user-images.githubusercontent.com/28384354/122369235-4c5d7200-cf5e-11eb-9280-f71286851823.png)

With  `--createEnumTabsWithId` :
![image006](https://user-images.githubusercontent.com/28384354/122369242-4d8e9f00-cf5e-11eb-867c-1552fe97006e.png)

> So that tools like ModelBaker nevertheless know which selection list belongs to which attribute (without having to parse the model itself), there is the metadata table "T_ILI2DB_COLUMN_PROP".
There you can see the type of an attribute (here "columnname") or in case of selection lists, which selection list is referenced by the attribute.

Since some users prefer to have the old way still, should we:
- give the user the possibility to select the option
- use the `ilicode` still, even with `--createEnumTabsWithId`

**Comment by signedav** [comment]
@gacarrillor any thoughts on that?

**Comment by gacarrillor** [comment]
@signedav, I can't really understand the issue. Could you please rephrase it?

Anyways, here some inputs from our project:
 
 + We don't (and won't) use il2db <= 3 anymore.
 + We'll always go for the `t_id` column in enumeration tables, i.e., ` --createEnumTabsWithId`. I think it's a recommended way of building DB relations.
 + The `enumDomain` entry in `t_ili2db_column` was only added [9 months ago](https://github.com/claeis/ili2db/commit/d235e98d940422a43a4699c258be53c19e38c5cf), whereas the model_parser exists [way before](https://github.com/opengisch/QgisModelBaker/commit/933ec310517d2b01f388cc450b6b48e8f590a901#diff-44d4438ac8ad20ca80eb8f319da09b28cb34cd2d5e1d0c351c49be49de8afa50) (namely, 2017).

**Comment by signedav** [comment]
Sorry. The "why" part is indeed missing in my description.

It's not about using ili2db <= 3. This was just to tell where in the model baker the "old" parameter is used still.

I agree that it's the usual way of DB relations, that you use IDs as FKs instead of values.

But still users requested the old behavior. I assume they just expect to have readable values in their enum-fields.

Do you know why `createEnumTabs` was "replaced"? Is it obsolete?

**Comment by m-kuhn** [comment]
As far as I can see the requirement is to be able to see the text value directly on the table where it's used (screenshots above only show where it's defined) using tools like db manager.
It should be fairly easy to implement. But will likely add a bit to maintenance effort.
The "old" one is per "domain type" the "new" one is per "base domain type", so we should expect the schema layout to change a bit, it's hard to say if/when this will have consequences.

**Comment by gacarrillor** [comment]
I might be still misunderstanding the point, but anyways, this is my opinion:

> But still users requested the old behavior. I assume they just expect to have readable values in their enum-fields.

You mean, in the field value stored in the DB, right?

In that sense, yes, that could be an option for those users: _Do you prefer a proper `id` as relation's FK or a text value (i.e., `iliCode`)?_ That would basically toggle the `--createEnumTabsWithId` parameter, but... read below.

> Do you know why createEnumTabs was "replaced"? Is it obsolete?

I don't know if `createEnumTabs` + `createFKs` will create a proper FK for domain-table relations. See [here](https://github.com/claeis/ili2db/issues/19) some discussion. I guess that's what we need to guarantee before offering the aforementioned option. 


Moreover, in an scenario of Enum inheritance, things are more difficult. See https://github.com/opengisch/QgisModelBaker/pull/438 for an example where neither `itfCode` nor `iliCode` would work as FK (unless you know whether you're referring to the parent domain or to the child one), because they are not unique in the referenced table.

**Comment by signedav** [comment]
Okay thanks for the explanation. I thought it was just about using ids instead of text values as FKs.

> I don't know if `createEnumTabs` + `createFKs` will create a proper FK for domain-table relations. See here some discussion. I guess that's what we need to guarantee before offering the aforementioned option.

But as far as I understand tha (with the linked issue) there have not been any FKs created before the introduction of `--createEnumTabsWithId`. So there where no relations created by the Model Baker and with this no widgets to select the value? Or has this been made by the model parser functionality?

In any case the step back to `--createEnumTabs` will bring us back to parse the model again?

**Comment by gacarrillor** [comment]
> But as far as I understand that (with the linked issue) there have not been any FKs created before the introduction of --createEnumTabsWithId. So there where no relations created by the Model Baker and with this no widgets to select the value? Or has this been made by the model parser functionality?

Right, the model parser in Python was created just for that, so that users could have relationships configured in their projects (at the QGIS user level), at least until ili2db did it properly at the DB level.

> In any case the step back to --createEnumTabs will bring us back to parse the model again?

I just tried it out, removing `--createEnumTabsWithId` for running a schema import in a GPKG and didn't get the ENUM relations. So, yes, I'm afraid we'd need to use the model parser if users don't want the `t_id` as FK.

However, we'd need to deal with the scenario in https://github.com/opengisch/QgisModelBaker/pull/438, which is a bit more complicated than what the model parser used to deal with.

**Comment by signedav** [comment]
Thanks @gacarrillor for the explanation. I think everyone agrees that it's not the good way to implement the old behavior again - still users see benefits from the old one, why I close this "technical" issue and open that one #511 for discussions what is UX-wise worse and what Model Baker could improve.
