### ISSUE TITLE
Layout management in forms

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#504]
For example here, scrollbars should not be visible.
On the "punkt" tab, there is enough space, it's only widened by the "Allgemein" tab

![Screenshot from 2021-06-22 14-30-16](https://user-images.githubusercontent.com/588407/122924760-66d08a80-d366-11eb-8575-db173207bf59.png)

**Comment by signedav** [comment]
Should have a scroll view on every tab.

**Comment by signedav** [comment]
And have a look to make widgets smaller that need so much space.

**Comment by domi4484** [comment]
Pr opened for scroll view on each tab:
https://github.com/qgis/QGIS/pull/44708

**Comment by domi4484** [comment]
- [x]  Scroll view issue fixed and merged into master
- [ ] Making widgets smaller still open

**Comment by domi4484** [comment]
> Making widgets smaller still open

This point was about making widgets such as spinboxes (numbers) less width. Now they use the entire width, and when an scrollbar is available the value number is not visible because it is right aligned. When the value is not visible it becomes easy to think that no value is set.
See screenshot below:
![Peek 2021-11-19 14-45](https://user-images.githubusercontent.com/9881900/142632744-d12bf895-f376-4dda-8770-1a64d34002e4.gif)

Ideally this widgets should not use all available space but only get as width as the `sizeHint`
Which widget should not expand?
- [x] Range
- [x] Date/Time
- [ ] Classification (combobox)?
- [ ] ...?

**Comment by signedav** [comment]
In the workshop I noted:
> And have a look to make widgets smaller that need so much space.

@romefi What is the need for the optimization for the widget size? I think with fiddle it out, implementation, PR discussion etc. it will take at least a day or two. Should this time be invested on that or is it low priority after the scroll-part is fixed?

**Comment by romefi** [comment]
@signedav I think we go low priority and discuss it on our next meeting (I'll make a label for that)

**Comment by signedav** [comment]
If the widget size would be higher prio again, we could open a new issue for it.
