### ISSUE TITLE
Relations in multiedit: allow adding one child per feature

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/QgisModelBaker#507]
Use case tree management, it should be possible to add a new "maintenance" entry for each edited tree in multi edit.

**Comment by signedav** [comment]
Means support of relation editor widgets in multi edit mode.

Currently disabled: 
![image](https://user-images.githubusercontent.com/28384354/123694128-33579980-d859-11eb-8a81-5310bf696abf.png)

So it should create one child entry in the maintenance table per each edited parent feature, right?

**Comment by signedav** [comment]
Possible functions here would be:
- Add child for all selected parents
- Add child with geometry (same geometry for all) for all selected parents
- Link referenced parent (in many-to-many relation) to all selected parents

In case the newly created children are listed (all of them), they could be selected and deleted and changed etc. But is this part of this issue? How should it be displayed anyway?

What should be scope of this integration? Since it's extendable I would suggest to have only the create child functionality in the first step (without linking). How should all be displayed? Does it make sense to have all of the newly created children listed?

@m-kuhn What did we had in mind originally?

**Comment by signedav** [comment]
![image](https://user-images.githubusercontent.com/28384354/136021379-0a296436-bcdd-4b44-8017-b75ac2b9dea3.png)

**Comment by signedav** [comment]
See for many to many implementation #551

**Comment by signedav** [comment]
see https://github.com/qgis/QGIS/pull/45703

**Comment by domi4484** [comment]
Implemented in QGIS 3.24 with pr https://github.com/qgis/QGIS/pull/45703
