### ISSUE TITLE
Loading of additional manual relations from configuration file

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#589]
It would be very useful being able to load additional relations next to the relations derived from the data model.

Use case: Links to data in other data models (such as data from surveying (Amtliche Vermessung) linked to data from Grundbuch) where the data resides in completely different models and the link is through a stable ID (like EGRID).

It would be best if the additional relations could be loaded before the individual layer qml-Files are loaded so that the QML-Files can already use the additional relations.

I  don't know the relations internals too much - do we have issues with internal IDs (of layers  and relations definitions) that are referenced by the QMLs?

I don't know what the best file would be to store the relations configuration? Perhaps the `metaconfig.ini file` with a separate section for the relations containing the following information:
- Relation ID
- Relation Name
- Relation Strength
- Referenced Layer
- Referenced Field(s)
- Referencing Layer
- Referenicng Field(s)

Subsequently loaded QML files need to be able to reference the additionally loaded relations, e.g. in the relation reference widgets.

**Comment by signedav** [comment]
Since this can be achieved when having the relation widgets defined in the QML files (QGIS creates the missing relations) this is not that high priority anymore. But be aware: this only works with stable layernames and you cannot add relations without having widgets defined for it. It works with a QGIS fallback function and is kind of black magic A proper implementation in Model Baker would make sense after all someday somehow. Some notes I made here as well https://gist.github.com/signedav/c14a819b9ef8883ae829506d181f4e36

**Comment by signedav** [comment]
### Update

It's not real black magic fallback. It's implemented clearly as "Relations" in the exporting:
![image](https://user-images.githubusercontent.com/28384354/231373856-d8fded5b-e082-4cc8-83c4-48d031f34534.png)

It's just only working on (a) the referencing layer (child) and (b) with files (tested with qml) and not with copy paste.
