### ISSUE TITLE
Format of BID / creation of Baskets

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#599]
When a BID (Basket-ID, t_ili_id in t_ili2db_basket) is generated by Model Baker, it's an UUID. We noticed, that export fails, if the BID starts with a number.

`Error: Laermempfindlichkeitsstufen_V1_2.Geobasisdaten: tid 36ba4cf3-4d3b-4c4f-bf2b-057e3a467b79: value <36ba4cf3-4d3b-4c4f-bf2b-057e3a467b79> is not a valid BID`

Does it start with a letter, the export works.

The [Referenzhandbuch of Interlis2](https://www.interlis.ch/download/interlis2/ili2-refman_2006-04-13_d.pdf) says the BID has to be an OID (see page 127), if the output is incremental. Which is usually not the case. But still would somehow explain the error.

@signedav @zigertiger: Was that ever a topic in your discussions?

**Comment by signedav** [comment]
I thought an `UUIDOID` as OID is allowed. Thanks for the input.

**Comment by zigertiger** [comment]
INTERLIS reference manual (2.3):

p.80 / 3.3.1: `XML-ID= XML-ValueDelimiter [XML-NcName ':' ] ( Letter | Digit | '_' ) { Letter | Digit | '_' | '-' | '.' } XML-ValueDelimiter.`

p.87 / 3.3.6: `... 'BID=' XML-ID ...`

That means that a valid BID _must_ start with _either_ a letter, a digit (0..9) or an underscore. Thus, UUID (gen. 4) is correct.

**Comment by romefi** [comment]
Thanks @zigertiger for the clarification. So the error with BID = 36ba4cf3-4d3b-4c4f-bf2b-057e3a467b79

`Error: Laermempfindlichkeitsstufen_V1_2.Geobasisdaten: tid 36ba4cf3-4d3b-4c4f-bf2b-057e3a467b79: value <36ba4cf3-4d3b-4c4f-bf2b-057e3a467b79> is not a valid BID`

is wrong, because it's a valid BID? Means a bug in ili2db?

@claeis: What do you think?

**Comment by claeis** [comment]
It depends on the ili-model:

Does the TOPIC have a BASKET OID AS...definition? If no: no leading 0..9 allowed

If yes: is the referenced OID domain text (no leading 0..9) or numeric (leading 0..9 allowed) or INTERLIS.UUIDOID (leading 0..9 allowed)?

In the case of TOPIC Laermempfindlichkeitsstufen_V1_2.Geobasisdaten there is a BASKET OID AS and it's a text domain: so no leading 0..9 allowed.

**Comment by signedav** [comment]
Okay, so the OID definition needs to be considered by Model Baker when creating "new" baskets.

**Comment by romefi** [comment]
Yes, it should. Or at least be editable on the Dataset-Manager. The same problem occurs also to TID, I think it's close related to https://github.com/opengisch/QgisModelBaker/issues/340. 

My suggestion:

1. Make t_ili_id editable -> it's on the users responsibility, to fill in the right value
2. Look for a generic way to read the expected type of OID and make, if possible, fill in automatically the right value

**Comment by signedav** [comment]
We currently do not provide a mask to the user to fill up the baskets generated resulting on the topics with the dataset "Baseset" to be able to start with an empty database. We do really need a solution on that but at the moment I suggest you the workaround:
- Let Model Baker create the baskets automatically (using UUIDs)
- Change them in de database directly, before you add data
The table t_ili2db_baskets is not hidden currently in the project but still read only. This becasue mutations should not be made by the end user. Should this table be writable until we have a solution @romefi ? Or is the workaround by editing the database cool for you at the moment?

**Comment by signedav** [comment]
Best would be when Model Baker has the ability to create valid OIDs.

Is there any information about the BASKET OID in the t_ili2db* tables @claeis ?

**Comment by romefi** [comment]
> Should this table be writable until we have a solution @romefi ? Or is the workaround by editing the database cool for you at the moment?

Think it would more cool to make the table writable until we have a propper solution. Not everyone is such a poweruser and is able and capable of changing this in the database iteself.

**Comment by claeis** [comment]
There is no information about the BASKET OID in the t_ili2db* tables. But see claeis/ili2db#440

**Comment by signedav** [comment]
Some thoughts:

With the implementation in ili2db (with upcoming 4.7) Model Baker will be able to check what kind of BASKET OID should be created. With UUID no problem, with the other OID types Model Baker can create model-conform ids but cannot assure if they are correct in the users context. 
I would love to hide the basket-table in future versions of Model Baker, because this is not something the user should be able to edit manually. But because I don't see a way around that the user needs to be able to edit the ids, we might need to create a "Basket Manager" in the Dataset Manager, so the user can fill up the ids of the baskets. Thanks to the BASKET OID definition in the model, Model Baker can validate the users entry against a pattern.

**Comment by signedav** [comment]
Meanwhile t_ili2db_baskets stays editable and on creating the baskets with the Dataset Manager an information appears:
![image](https://user-images.githubusercontent.com/28384354/146751112-54904cec-f1d6-4bf4-b8d2-64d9214cda01.png)

**Comment by signedav** [comment]
Maybe we can think about a solution for creating baskets. Since it would be nice as well to be able to choose for what topic/dataset subset should a basket be created. Together with that, the structure of the BID should be recognized and edited (e.g. prefix) by the user.

Another scope but same issue concerning the "generation" of OIDs is decribed here #340
