### ISSUE TITLE
Identifying basket at export

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#600]
When a dataset has baskets, it's difiicult to choose the right one at export, as topic can be the same and t_ili_id is often an UUID. Would be nice to have attachmentkey listed as well, so it's more easy to choose the right basket. Assume same applies to import (didn't test yet).

![image](https://user-images.githubusercontent.com/26796989/144182497-ee1eb418-ff5d-4af7-bc07-81dd360a24db.png)

**Comment by gacarrillor** [comment]
For reference:

  + We'd need to keep an eye on the eventual removal of the `attachmentkey` column. See this note in the ili2db docs: https://github.com/claeis/ili2db/blob/d56b1d66ebade1e94fba0d79c385b3e77ef1bf9e/docs/ili2db.rst?plain=1#L1698

  + For the `Data Import` operation, users select datasets. They can open the `Dataset Manager` and there the `attachmentkey` is not shown.

**Comment by signedav** [comment]
Concerning the removal of the `attachmentkey`. I'm not sure if it's a good identification anyway. E.g. when the basket is created by Model Baker it's always "QGIS Model Baker".  Of course this could be made editable for the users. Anyway, since ili2db is going to remove it we might should ask them (Claude) if there are other possibilities like "Description" to add, if this is really requested.

But still, usually you have a descriptive dataset name and a topic and this should be identificating it already clearly. Ain't that the case @romefi ?

Concerning the `Data Import` this is not true @gacarrillor The basket is not (yet) listed in the Dataset Manager, since it's created with the import. Or do I misunderstand?

**Comment by gacarrillor** [comment]
> Of course this could be made editable for the users.

Right now the `attachmentkey` is editable via `LayerTree -> system -> T_ILI2DB_BASKET`.

> Concerning the Data Import this is not true @gacarrillor The basket is not (yet) listed in the Dataset Manager, since it's created with the import. Or do I misunderstand?

Yes, baskets are created when you import the data, you should only select a dataset (as I said). I was just adding info to what @romefi stated in the issue description:

> Assume same applies to import (didn't test yet).

----------

Having said that, perhaps we could hide the `Manage baskets of selected dataset` button if the `Dataset Manager` is called from the `Data Import Configuration` page, where users should only select/create datasets. In other words, why we allow to create baskets in that context?

![image](https://github.com/opengisch/QgisModelBaker/assets/652785/a3826857-276f-4ec7-bb36-f337205a3ad4)

**Comment by signedav** [comment]
> Having said that, perhaps we could hide the Manage baskets of selected dataset button if the Dataset Manager is called from the Data Import Configuration page, where users should only select/create datasets. In other words, why we allow to create baskets in that context?

Agree.

**Comment by gacarrillor** [comment]
> Agree.

Just added a commit to handle this context, please have a look. Note I'm using the `objectName` instead of creating a context object, which could probably be too much for the use case (I didn't see other custom context objects in the code).
