### ISSUE TITLE
Models in Repository https://405.sia.ch/models not listed

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#646]
The Repository https://405.sia.ch/models is part of https://models.interlis.ch/ilisite.xml, but the models in https://405.sia.ch/models are not listed in Model Baker:

![image](https://user-images.githubusercontent.com/26796989/159232673-21cc9b15-dcd9-48e4-ae49-aba76bd0951e.png)

Is this because https://405.sia.ch/models uses `https`? Could this be fixed?

**Comment by signedav** [comment]
Are they available with ili2db when passing the model in the command?

**Comment by romefi** [comment]
Thanks @sjib for testing. That's weird, so it works when the repository is given as model-folder, but not over https://models.interlis.ch/ilisite.xml. @signedav could that be a "bug" in the way Model Baker searches for models in sub-sites? Goal must be that all models in the sup-repositories are listet when you search in "Model oder Transferdatei".

@sjib i agree, would be nice if the VSA-DSS models would also be available. Therefore it would be nice, if https://www.vsa.ch/models/ would also be listed in https://models.interlis.ch/ilisite.xml. Could you arrange that?

**Comment by signedav** [comment]
No idea. Thanks for your research. I'll have a closer look later this week.

**Comment by sjib** [comment]
@romefi As the VSA models inherit the SIA Base models the connection should work via sia repository and the ilisite.xml there where interlis is the parentsite and VSA the subsidiarySite. All tests with ilic have shown that this works fine like this. So I would start checking on https first.

**Comment by romefi** [comment]
@sjib thanks for the clarification. Then it should work when Model Baker works properly with https.

**Comment by signedav** [comment]
I found out what the problem is. It's not the `https` - this works fine with e.g. https://models.geo.llv.li

It's the subfolder in the url without a trailing slash. (In your example @sjib defining it in the model baker settings you have this slash. That's why it's working there).

In the used python function it recognizes it without any slash in the end as a file, and replaces `/models` with `/ilimodels.xml`:
```
>>> urllib.parse.urljoin("https://405.sia.ch/models", "ilimodels.xml") 
"https://405.sia.ch/ilimodels.xml"
```

I think we can assume that the value in the RepositoryLocation is always a directory and never a file (like e.g. `https://405.sia.ch/index.html` and just add a slash if not existing.

**Comment by romefi** [comment]
Good to hear it's not an `https`-Issue.

@signedav I agree with your assumption. Not sure if it's definied somewhere, but it seems that it's at least common sense, that the RepositoryLocation is a folder. Therefore I would fix it as you suggested.
