### ISSUE TITLE
Removal of    "--createTidCol"   "--importTid" from the default ili2db-command

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#697]
I guess it is more a discussion than an issue:

Problem:
With the current settings, one has to insert a "t_ili_id" for every object which is created to be able to perform a xtf-export. Otherwise, the Error message "...Class xx.xx has to have an OID" will be reported. 

An INTERLIS- and or QGIS-Rookie which only wants to bake a project and collect Data in this project, might not understand the oid concept and the purpose of the rows "t_id" and "t_ili_id". The user also doesn't know how ili2gb works in the Background of the Model Baker and in my view he doesn't have to.

Proposal:
Removal "--createTidCol"   "--importTid" from the default ili2db-command

Effect:
- The "simplest" User-Group is able to generate a project, collect and export data without a deep knowledge of ili2db/INTERLIS. And don't have to care about the id's.
- To work with  stable OID is a decision taken by specialists for whom it should be no problem to change the ili2db command

Another option to solve the problem would be to automatically generate the OID t_ili_id" as proposed here: 
https://github.com/opengisch/QgisModelBaker/issues/340 .

**Comment by signedav** [comment]
When an OID is defined in the model, Model Baker cannot do anything. t_ili_tid is created and mandatory. That's what @romefi described.

When Model Baker sets the `--createTidCol` the t_ili_tid is created, but not mandatory. You could leaf it empty.

But - and I think the this is the thing that could be discussed here - on export a default parameter `--exportTid` is set. So even when the t_ili_tid is not mandatory, the export requires them. Maybe that's your use case @threalslimtobeeee 

So why this parameter is set? Because often people need to use t_ili_tid even when no OID is defined in the model and expect that they are exported as well (because there is this column).

We could solve it that Model Baker sets a default value on the field (e.g. UUID) when no OID is defined (this can be a small part of #340). Or we could make this parameter optional again (what would make the GUI more complicated).

**Comment by signedav** [comment]
The use case described here is when having no OID defined in the topic. This use case is not mentioned here #340 but still part of it. Model Baker sets the `--createTidCol` so it should provide a default value for t_ili_tid IMO. This could be solved unrelated to #340. We would need to (1) check if this t_ili_tid column has an OID defined (`t_ili2db_column_prop` with tag `ch.ehi.ili2db.oidDomain`) and if it's not existing, we should set as default expression a UUID (in gpkg and postgres as well).

**Comment by threalslimtobeeee** [comment]
Thanks for the quick fix!

**Comment by signedav** [comment]
Check it out in the current beta 7.1.7
