### ISSUE TITLE
New attributes "identifyable" and "searchable" in layertree.yaml

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#711]
Introduce new layer attributes "queryable" in "layertree.yaml" to set the  "queryable" parameter in the project properties "data source" tab:

Part of a layertree.yaml file:

```
    - "Hintergrundkarten":
        group: true
        checked: true
        expanded: true
        identifiable: false
        searchable: false
        definitionfile: "../layertree/hintergrundkarten.qlr"
```

![image](https://user-images.githubusercontent.com/884476/178445610-a02c5f11-967a-4b54-b111-a3a03bc20db7.png)

Note that this should also set the queryable parameter for a whole layergroup, if loaded from an external .qlr file (like in the example).

**Comment by signedav** [comment]
PyQGIS Note - Searchable, Identifiable, ReadOnly etc. are flags:
```
if layer.flags() & QgsMapLayer.Searchable:
    print("The layer is searchable.")
else:
    print("The layer is not searchable.")
 ```

**Comment by signedav** [comment]
Is "private" resolving "hidden" (#649)

**Comment by gacarrillor** [comment]
Since QML and QLR files can be used as toppings, and given that they contain whether a layer is searchable and/or identifiable, this issue is considered solved. It won't be available as individual YAML property (e.g., identifiable: true), but should be used inside QML/QLR files, which is already supported by Model Baker.

Related upstream fix: https://github.com/qgis/QGIS/pull/59141

There is a second part in this issue, which is not yet addressed:

> Note that this should also set the queryable parameter for a whole layergroup, if loaded from an external .qlr file (like in the example).

If we can confirm that this is still required, feel free to reopen, @signedav.
