### ISSUE TITLE
Validator: Pan to coordinates

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#747]
On automatic pan it pans to the feature geometry centroid, if the OID is provided by ili2db, and if not **then no pan is performed (no pan on coordinates yet)**. On automatic zoom it zooms to the features geometry, if the OID is provided by ili2db, and if not then to the coordinates with the extend of 10 map units. (1)

The request is not only that it should pan to the coordinates when no OID available, but to do this as the preferred way. (2) Means pan to coordinates, if no coordinates then to feature geometry (centroid).

**Comment by signedav** [comment]
1. Coord and OID
2. Only OID
3. Only Coord

**Status Quo:**
On automatic pan:
1. Pan to features centroid
2. Pan to features centroid
3. Nothing

On automatic zoom:
1. Zoom to features geometry
1. Zoom to features geometry
2. Zoom to coordinates with an extend of 10 map units


**Status Futura:**
On automatic pan:
1. Pan to coordinates
2. Pan to features centroid
3. Nothing

On automatic zoom:
1. **Zoom to features geometry or zoom to coordinates?**
1. Zoom to features geometry
2. Zoom to coordinates with an extend of 10 map units

**Comment by kingemir** [comment]
While validating, centroids are actually neither of interest nor helpful. We anyway are using in practice extremely high zoom factors while validating, and a pan to centroid leads thus to complete desorientation since edges tend to fall out of the extension of the current map. 
If the error is related to the edges or vertices, we need to see them. In our daily business, these cases represent over 95% (most cases are duplicate coord).
If the error is not related to edges or vertices as in your example, it doesn‘t matter wether panning happens to any vertice or to the centroid. For helping to identify the object, one can keep the flash-up function activated.

**Comment by signedav** [comment]
I see. Duplicate coord is in fact a common error. And the disadvantage of not pan to the coordinates in these cases is higher than the advantage of avoiding confusion when it pans to the "first" coordinate on a non-geometric error. I agree on that.

**Comment by signedav** [comment]
What about the zoom? Should it prefer the coordinates there as well?

**Comment by kingemir** [comment]
yes, also for zoom

**Comment by signedav** [comment]
Okay. Maybe in future ili2db provides us kind of types we can take into account. But for the moment it will be done like this: #770

Thanks for your feedback @kingemir
