### ISSUE TITLE
Export: Don't disable succeeded export session

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#748]
![grafik](https://user-images.githubusercontent.com/28384354/199767398-902ea150-73af-49a1-a434-1b3f6c780841.png)

On going back and forward again it's still disabled. Only when something changes it's reset. But maybe one wants to "Edit Command".

**Comment by signedav** [comment]
@kingemir What is the use case to run it again after going back and forward again, without changing anything? Or is it only for the case with "Edit command"?

**Comment by kingemir** [comment]
@signedav No it's independent of cases with "Edit command". 
Example use case: 

1. You export with success using Model Baker. 
2. You upload the exported xtf to a validator run by the government. 
3. You get some validation errors. (since governmental validators implement more checkers than what's defined in the ili model).
4. You keep the Import/Export Wizard window open while you clean your data from the errors. 
5. You export again with the same export settings you set before

**Comment by signedav** [comment]
Okay thanks.
