### ISSUE TITLE
Libs Folder in Plugin-Ci

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#750]
Currently the libs folder is not added to the released plugin. At the moment, I need to do it manually.

Add this step in release in continous_intergration.yml

```
      - name: Package PyPI Packages
        run: |
          sudo ./scripts/package_pip_packages.sh
```

But the plugin ci needs to allow libs folder because otherwise the libs folder is missing.

**Comment by 3nids** [comment]
At the moment _qgis-plugin-ci_ works on a git architecture using git archive and supports submodules.

I'm not even sure how your current workflow works since it seems the libs folder is never committed?

How would you expect this to work? By specifying depedencies to be added in `.qgis-plugin-ci` ?

**Comment by signedav** [comment]
Naively I though it's possible to run `./scripts/package_pip_packages.sh` on packaging. 

But if a libs folder is needed on this repo I could run it on a merge to master action as well...

**Comment by signedav** [comment]
> But if a libs folder is needed on this repo I could run it on a merge to master action as well...

Is this the way to go @3nids in your opinion?

**Comment by 3nids** [comment]
Basically, I see 2 approaches:
1. you can just git add & commit your lib folder just before running plugin_ci
2. use what Matthias did here: https://github.com/opengisch/qgis-plugin-ci/pull/230
