### ISSUE TITLE
 Toppings: Possible incompatibilities (gpkg/postgis)

### ISSUE THREAD

**Issue by threalslimtobeeee** [opengisch/QgisModelBaker#759]
Toppings which are exported from a project which is based on a PostGIS schema will not work properly when you try to use them to generate a project and import a model into a gpkg. 

Example: The table name for dataset table in PostGIS is "t_ili2db_dataset" in gpkg it is "T_ILI2DB_DATASET". This has consequences on the "yaml" file.

Problem: A user, who did not create a topping and has no interest in browsing and reading config files, does not know if a Topping will work for him. 

Possible solution:The user is informed for which data format the topping was created

**Comment by signedav** [comment]
Yes. GeoPackage toppings are (often) not compatible with PostGIS toppings. KbS Models for example have multiple geometries in one class what lead to a completely different layer tree. 

- [ ] Still it can be interesting to check out, in what cases toppings are compatible for both or what Model Baker can do to achieve that (only renaming the dataset table would be an easy one but I guess there are more (e.g. t_ili_tid naming and the t_id's default value) - not sure if it's possible at all.

- [ ] To have an info about what database the topping is intended for could be achieved in /1 the naming convention (e.g. add the database-info to the default project name in the exporter and then let it up to the user to keep it or not (consider this #756), or /2 having kind of a fix parameter in a toppingfile (e.g. projecttopping (yaml)) that is displayed in the metaconfig / topping selection as well.

**Comment by signedav** [comment]
Another idea would be to use a `category` in the ilidata.xml (`DatasetIdx16`). But we need to be careful concerning backwards compatibility.

**Comment by signedav** [comment]
Maybe the `category` is a solid approach :thinking: 

If we have the info about the db, we can filter them. If not, we don't. If an entry does not have those information (because of created before this implementation) we show it as well. 
In case we would be able to create a topping for multiple db-systems we could add all of them or none, to be listed everywhere.

So metaconfigs and projettoppings should have this category in future.

#### Note for myself:
Es würde wohl Sinn machen nicht mehr `http://codes.opengis.ch/modelbaker` zu verwenden, sondern eher `http://codes.modelbaker.ch/tool` oder dann auch `http://codes.modelbaker.ch/dataprovider/gpkg`...

#### Steps:
- change `http://codes.opengis.ch/` to `http://codes.modelbaker.ch/` 
- introduce `http://codes.modelbaker.ch/dataprovider`
- filter irrelevant metaconfigs in the current implementation on the import source page
- filter irrelevant projecttoppings in the future implementation on project generate page
