### ISSUE TITLE
Topping Exporter: ili2db setting "nameByTopic" not taken into account

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#764]
In the Usability-Hub Exporter section dealing with "ili2db Settings Selection", where the mode is "read settings from existing schema", it seems like the "nameByTopic" option is not correctly set and read:

![image](https://user-images.githubusercontent.com/884476/205318847-9a9c8fa4-f064-461a-a1b6-93f972887522.png)

In the resulting table this setting is missing:

![image](https://user-images.githubusercontent.com/884476/205319108-72789efc-c12e-431d-8511-ee566cdef8cf.png)

**Comment by signedav** [comment]
Currently only the parameters are parsed that Model Baker is using (default parameters or the ones from the setting). The effort to get all the parameters according to the tags in the table is quite high, I guess. That's why we narrowed it down to the settings made by Model Baker - so when a schema is created with Model Baker, all the considered settings are taken into the topping.

**Comment by signedav** [comment]
Actually you would only need to add those manually you added on the original schema import to the ones set by Model Baker, no?

**Comment by signedav** [comment]
And yes. You have to add the 10% manually in the ini at the moment.

**Comment by signedav** [comment]
Maybe a good compromise would be to be able to add parameters (and not changing the others).

**Comment by signedav** [comment]
Opened this instead #796
