### ISSUE TITLE
Create Button

### ISSUE THREAD

**Issue by geckoGIS** [opengisch/QgisModelBaker#803]
Hi

Users often do not perceive the create button as a button:

![image](https://user-images.githubusercontent.com/45884483/235887950-95e7f324-19f1-45b0-a432-4d0c9c0de69e.png)

The button only becomes visible when you move the mouse.

![image](https://user-images.githubusercontent.com/45884483/235888351-5872587e-fbb4-42e4-82da-e7d0c8fe150b.png)

Maybe it would be easier for the user if the create button is permanently visible.

Thanks
Marleen

**Comment by signedav** [comment]
This "flat" design is given to this kind of buttons (CommandLinkButton). They are usually used to "replace"/"give alternatives" to the next button to got to the ***next step***. Classic example is the intro page of the wizard:
![image](https://user-images.githubusercontent.com/28384354/236136587-8ba3c935-1165-407b-a51b-466459264309.png)

It would be possible to use a normal button here, but IMO this is less intuitive since it more looks like an additional step (instead of the ***next step***):
![image](https://user-images.githubusercontent.com/28384354/236136221-347e99f2-76e7-49c3-b872-d9f802c923d6.png)

Or maybe it would be possible to override the paint-function to have it always enabled (like you suggest), but I'm not sure if I would do this, since it can be confusing as well, when the user is used to have it "flat".

**Comment by geckoGIS** [comment]
Hi,
Thank you for your feedback
I also think that the normal generate button is not an option based on your explanation.
I have noticed that especially new QGIS Model Baker users click the "finish" Button too quickley.
It is maybe a "nice to have" option (override the paint-function).

**Comment by signedav** [comment]
Maybe there is another way to avoid that the user clicks finish. Maybe no "Generate" button above and instead of having a "Finish" option having two options "Generate and close" and a "Close without generate" - but this idea needs to be evaluated first. Not sure if it's a good one.
